version: "3.10"
  services:
    worker:
      build: .
        environment:
          - APP_ID=${APP_ID}
          - API_HASH=${API_HASH}
          - SESSION =${SESSION }
          - FROM_=${FROM_}
          - TO_=${TO_}
    
